### ISSUE TITLE
bit-width issue in model prepared for QAT

### ISSUE THREAD

**Issue by kartikgupta-at-anu** [ModelTC/MQBench#137]
I am using the QAT scripts for ImageNet training with 4-bit QAT. I tried both academic and tensorrt backend with following config passed to prepare_by_platform().

extra_qconfig_dict:
  w_observer: LSQObserver
  w_fakequantize: LearnableFakeQuantize
  w_qscheme:
    bit: 4
    symmetry: True
    per_channel: False
    pot_scale: False
    symmetric_range: True
  a_observer: LSQObserver
  a_fakequantize: LearnableFakeQuantize
  a_qscheme:
    bit: 4
    symmetry: True
    per_channel: False
    pot_scale: False
    symmetric_range: True

When I check the network in the forward pass, the bit-width is 3 instead of 4.

**Comment by PannenetsF** [comment]
I just checked the prepare process with the provided config, for weight:
```
 (conv2): Conv2d(
      64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
      (weight_fake_quant): LearnableFakeQuantize(
        fake_quant_enabled=tensor([1], device='cuda:0', dtype=torch.uint8), observer_enabled=tensor([1], device='cuda:0', dtype=torch.uint8), quant_min=-8, quant_max=6, dtype=torch.qint8, qscheme=torch.per_tensor_symmetric, ch_axis=-1, scale=Parameter containing:
        tensor([1.], device='cuda:0', requires_grad=True), zero_point=Parameter containing:
        tensor([0.], device='cuda:0', requires_grad=True)
        (activation_post_process): LSQObserver(min_val=inf, max_val=-inf ch_axis=-1 pot=False)
      )
    )
```
for acti:
```
LearnableFakeQuantize(
  fake_quant_enabled=tensor([1], device='cuda:0', dtype=torch.uint8), observer_enabled=tensor([1], device='cuda:0', dtype=torch.uint8), quant_min=-8, quant_max=6, dtype=torch.qint8, qscheme=torch.per_tensor_symmetric, ch_axis=-1, scale=Parameter containing:
  tensor([1.], device='cuda:0', requires_grad=True), zero_point=Parameter containing:
  tensor([0.], device='cuda:0', requires_grad=True)
  (activation_post_process): LSQObserver(min_val=inf, max_val=-inf ch_axis=-1 pot=False)
)
```

Though not a full 4bit, it is much more than 3 bit. 

I found that you use symmetric range and symmetric quant at the same time, which resulted in the non-symmetric quantization. The source could be checked here https://github.com/ModelTC/MQBench/blob/main/mqbench/observer.py.

**Comment by kartikgupta-at-anu** [comment]
When I check the unique values after quantization in the graph module during forward pass, they are exactly 3 bits, i.e. 8 unique values.  I check this by printing the values of input after quantization in the graph code generated by fx. There is also a parameter called bit-width which is set to 3 in the graph. I could not figure out how that bit-width parameter is estimated as its not set same as one in the config..

Can you suggest how can i exactly use full 4 bits?

**Comment by PannenetsF** [comment]
** they are exactly 3 bits, i.e. 8 unique values.** I wonder which 7 values were shown in your model. 

You can follow the example we provided at imagenet_example: 
```
extra_prepare_dict:
    extra_qconfig_dict:
        w_observer: MSEObserver
        a_observer: EMAMSEObserver
        w_fakequantize: AdaRoundFakeQuantize
        a_fakequantize: QDropFakeQuantize
        w_qscheme:
            bit: 4
            symmetry: False
            per_channel: True
            pot_scale: False
            p: 2.4
        a_qscheme:
            bit: 4
            symmetry: False
            per_channel: False
            pot_scale: False
            p: 2.4
```
Unless some hardware(backend) needs a symmetric_range like [-7,7] rather that [-8,7], we do not set this attribute. That is, if you use academic backend, do not use this.
